name: CI Nix

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - name: Install omnix
        run: nix --accept-flake-config profile install "github:juspay/omnix"
      - id: set-matrix
        run: |
          MATRIX="$(om ci gh-matrix --systems=x86_64-linux,aarch64-darwin | jq -c .)"
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  nix:
    needs: configure
    runs-on: ${{ matrix.system == 'x86_64-linux' && 'ubuntu-latest' || 'macos-latest' }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@v3
        timeout-minutes: 3
        continue-on-error: true
      - name: Install omnix
        run: nix --accept-flake-config profile install "github:juspay/omnix"
      - name: Omnix CI
        run: om ci run --systems "${{ matrix.system }}"

  cross:
    name: cross (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/determinate-nix-action@v3
      - uses: DeterminateSystems/flakehub-cache-action@v3
        timeout-minutes: 3
        continue-on-error: true
      - run: nix build .#${{ contains(matrix.target, 'apple') && 'pagers' || format('pagers-{0}', matrix.target) }}
